"""new tables

Revision ID: bcfc313d33cc
Revises: 4dfafa3bb1be
Create Date: 2022-04-18 17:26:14.439545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcfc313d33cc'
down_revision = '4dfafa3bb1be'
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_user_email', table_name='chat_user')
    op.drop_index('ix_chat_user_id', table_name='chat_user')
    op.drop_index('ix_chat_user_nickname', table_name='chat_user')
    op.drop_table('chat_user')
    op.drop_index('ix_message_id', table_name='message')
    op.drop_index('ix_message_text', table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
